# syntax=docker/dockerfile:1

FROM cpasjuste/pacbrew

RUN git clone --recursive https://github.com/PacBrew/pacbrew-packages.git
RUN chown -R pacbrew:pacbrew pacbrew-packages
RUN cd pacbrew-packages && su -c "./pacbrew.sh" -g pacbrew pacbrew

